### ISSUE TITLE
Space character in %AppDir% error

### ISSUE THREAD

**Issue by stanolacko** [farin/JCloisterZone-Client#39]
There is issue when user name containc space character " ".
Images for tiles are not read and game crash.

Issue found by user Leven on CarcassonneCentral.com
https://www.carcassonnecentral.com/community/index.php?topic=5549

**Comment by farin** [comment]
Tested on win and space charecte in App and seems to be ok

**Comment by farin** [comment]
needs more investigation

**Comment by farin** [comment]
can be issue with passing file paths to engine?

**Comment by farin** [comment]
already fixed
