### ISSUE TITLE
Bridge placement over meeple

### ISSUE THREAD

**Issue by stanolacko** [farin/JCloisterZone-Client#42]
Some positions of meeple are direct in Bridge placement.
![image](https://user-images.githubusercontent.com/1910456/149399600-8c6d807a-0e54-4cbf-b237-d15a6e941b2b.png)
How to solve it?
Screenshot from 5.9.1

**Comment by farin** [comment]
won't fix for now
too much effort to solve it and is real issue only for black meeples (as for other colors it can be easily recognized if meeple is below or above)

**Comment by farin** [comment]
clean solution may be define alternative posiiton ifor meeple for case when bridge is present
